<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.3.1" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>36baab69-36d2-44fa-9292-bf778073a2ab</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AttendanceSystem.Auth.API\AttendanceSystem.Auth.API.csproj" />
    <ProjectReference Include="..\AttendanceSystem.ImportFile.API\AttendanceSystem.ImportFile.API.csproj" />
  </ItemGroup>

</Project>
